name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image 1
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          tags: ${{ secrets.DOCKER_USER }}/image1:latest

      - name: Build and push image 2
        uses: docker/build-push-action@v4
        with:
          context: ./server/api-gateway
          push: true
          tags: ${{ secrets.DOCKER_USER }}/image2:latest

      - name: Build and push image 3
        uses: docker/build-push-action@v4
        with:
          context: ./server/flask-service
          push: true
          tags: ${{ secrets.DOCKER_USER }}/image3:latest

      - name: Build and push image 4
        uses: docker/build-push-action@v4
        with:
          context: ./server/express-service
          push: true
          tags: ${{ secrets.DOCKER_USER }}/image4:latest

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: "latest"
          project_id: ${{ secrets.GCP_PROJECT }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GCP_ZONE }} \
            --project ${{ secrets.GCP_PROJECT }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Install gke-gcloud-auth-plugin
        run: |
          curl -L -o gke-gcloud-auth-plugin-linux-amd64.tar.gz https://github.com/kubernetes-sigs/gke-gcloud-auth-plugin/releases/download/v0.13.2/gke-gcloud-auth-plugin-linux-amd64.tar.gz
          tar -xzf gke-gcloud-auth-plugin-linux-amd64.tar.gz
          sudo mv gke-gcloud-auth-plugin /usr/local/bin/

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/
