name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image 1
        uses: docker/build-push-action@v4
        with:
          context: ./client
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USER }}/client:latest

      - name: Build and push image 2
        uses: docker/build-push-action@v4
        with:
          context: ./server/api-gateway
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USER }}/api-gateway:latest

      - name: Build and push image 3
        uses: docker/build-push-action@v4
        with:
          context: ./server/flask-service
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USER }}/flask-service:latest

      - name: Build and push image 4
        uses: docker/build-push-action@v4
        with:
          context: ./server/express-service
          push: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_USER }}/express-service:latest

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI and install GKE auth plugin
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          install_components: gke-gcloud-auth-plugin

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} \
            --zone ${{ secrets.GCP_ZONE }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/ --recursive
